name: Test
on: [push]

jobs:
  Util:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test ./...

  Utils-Test:
    strategy:
      matrix:
        build: [
          fiber, gorm, http, hunch, time, token, types
        ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: |
          cd ${{ matrix.build }}
          go test ./...
  
  

  Utils-Benchmarks:
    strategy:
      matrix:
        build: [
          fiber, gorm, http, hunch, time, token, types
        ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: |
          cd ${{ matrix.build }}
          go test -bench=. -benchtime=1000x -benchmem ./...